# Generated by Django 4.2.7 on 2023-11-29 09:58

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="appuser",
            options={},
        ),
        migrations.AlterModelManagers(
            name="appuser",
            managers=[
                ("objects", user.models.AppUserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name="appuser",
            name="date_joined",
        ),
        migrations.RemoveField(
            model_name="appuser",
            name="email",
        ),
        migrations.RemoveField(
            model_name="appuser",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="appuser",
            name="groups",
        ),
        migrations.RemoveField(
            model_name="appuser",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="appuser",
            name="is_staff",
        ),
        migrations.RemoveField(
            model_name="appuser",
            name="last_name",
        ),
        migrations.RemoveField(
            model_name="appuser",
            name="user_permissions",
        ),
        migrations.AlterField(
            model_name="appuser",
            name="is_superuser",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="appuser",
            name="username",
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
